# copies in:
#  conf/
#  config-files/
#  macosx/config-files/
#  windows/config-files/
- require:
    - com.foundationdb.sql.LayerInfoInterface
    - com.foundationdb.server.service.dxl.DXLService          # Loads the DDL/DML JMX bean
    - com.foundationdb.server.service.stats.StatisticsService # Stats gathering
    - com.foundationdb.server.service.jmx.JmxRegistryService  # Turns on JMX for other services
    - com.foundationdb.sql.pg.PostgresService                 # SQL
    - com.foundationdb.sql.embedded.EmbeddedJDBCService       # Embedded JDBC
    - com.foundationdb.server.service.log4jconfig.Log4JConfigurationService
    - com.foundationdb.server.service.monitor.MonitorService
    - com.foundationdb.server.service.is.BasicInfoSchemaTablesService
    - com.foundationdb.server.service.is.StorageSchemaTablesService
    - com.foundationdb.server.service.is.ServerSchemaTablesService
    - com.foundationdb.sql.ui.SwingConsoleService  # Presents a simple UI
    - com.foundationdb.rest.RestService
- prioritize:
    - com.foundationdb.sql.ui.SwingConsoleService  # Show service progress ASAP
